# Generated by Django 4.2.4 on 2024-01-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="accounts.profile"
            ),
        ),
    ]
