# Generated by Django 4.2.4 on 2024-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_follows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-pk"]},
        ),
    ]
